version: '3.8'

services:
  test:
    build: ./test
    container_name: test
    networks:
      - app-network
    expose:
      - "8001"

  #gameplay:
  #  build: ./gameplay
  #  container_name: gameplay
  #  networks:
  #    - app-network
  #  expose:
  #    - "8002"

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "8000:80"
    depends_on:
      - test
      - userdata
    networks:
      - app-network

  userdata:
    build:
      context: ./userdata/app
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py makemigrations &&
           python manage.py migrate &&
           gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000"
      expose:
      - "8000"
    env_file:
      - ./userdata/.env.prod
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./userdata/.env.prod.db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
